# Generated by Django 4.1 on 2022-08-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='actual_path',
            field=models.CharField(max_length=100),
        ),
    ]
